#!/usr/bin/env python3

import sys

def factorise(num):
    for i in range(2,int(num**0.5)+1):
        if num % i == 0:
            return i, num // i
    return None, None

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Use: factors <file>")
        sys.exit(1)
    f_input = sys.argv[1]
    fh = open(f_input, "r")
    for line in fh:
        num = int(line.strip())
        x, y = factorise(num)
        print(f"{num} = {x} * {y}")
    fh.close()
